# Generated by Django 4.0.4 on 2022-06-20 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_applicant_death_cert_father_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='applicant',
            name='county',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='family_mothly_income',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='id_number',
            field=models.IntegerField(null=True, verbose_name='National ID number/Passport'),
        ),
        migrations.AddField(
            model_name='applicant',
            name='number_of_siblings',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='parents_occupation',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
