# Generated by Django 4.0.4 on 2022-06-23 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_applicant_approved_applicant_county_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='id_number',
            field=models.CharField(max_length=15, null=True, verbose_name='National ID number/Passport'),
        ),
    ]
