# Generated by Django 4.0.4 on 2022-06-15 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bursaryapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bursary_Parameters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter', models.CharField(max_length=300)),
                ('parameter_value', models.IntegerField()),
                ('bursary', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bursaryapp.bursary')),
            ],
        ),
    ]
