# Generated by Django 4.0.4 on 2022-06-16 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bursaryapp', '0002_bursary_parameters'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bursary_Parameters',
            new_name='BursaryParameter',
        ),
    ]
