# Generated by Django 4.0.4 on 2022-06-16 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bursaryapp', '0003_rename_bursary_parameters_bursaryparameter'),
    ]

    operations = [
        migrations.AddField(
            model_name='bursary',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
