# Generated by Django 4.0.4 on 2022-06-16 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bursaryapp', '0005_alter_bursary_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bursary',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
