# Generated by Django 4.0.4 on 2022-06-17 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bursaryapp', '0006_alter_bursary_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bursary',
            name='slug',
        ),
    ]
