# Generated by Django 4.0.4 on 2022-06-17 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bursaryapp', '0007_remove_bursary_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bursaryparameter',
            name='parameter',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='bursaryparameter',
            name='parameter_value',
            field=models.IntegerField(null=True),
        ),
    ]
