# Generated by Django 4.0.4 on 2022-06-18 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_username'),
        ('bursaryapp', '0008_alter_bursaryparameter_parameter_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_application', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField()),
                ('applicant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.applicant')),
                ('bursary_application', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bursaryapp.bursary')),
            ],
        ),
    ]
