# Generated by Django 4.0.4 on 2022-06-26 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bursaryapp', '0009_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
